version: '3.8'

services:
  parcinfo:
    image: darkmind64/parcinfo:latest
    container_name: parcinfo-app
    restart: unless-stopped
    ports:
      - "5010:5000"
    environment:
      - FLASK_DEBUG=0
      - PYTHONUNBUFFERED=1
      - RUNNING_IN_DOCKER=1
      - TZ=Europe/Paris
    volumes:
      - parcinfo-data:/data
      - parcinfo-app:/app
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"

volumes:
  parcinfo-data:
  parcinfo-app:
